daniel5151/gdbstub

- src/gdbstub_impl/mod.rs
- src/target.rs
Currently `gdbstub` only allows SIGTRAP signals to be used in stop reply packets, however there are other signals that are useful to report (in particular I want to report SIGSEGV).
This PR partially issue report with _a possible_ way of allowing this. However, maybe you want to have explicit enum variants for all reasonable stop reasons, and this technically a breaking change, so may need to wait to the next non-patch release.
> Allow stop packets with arbitary signal codes

- src/arch/mod.rs
- src/arch/riscv/mod.rs
- src/arch/riscv/reg/mod.rs
- src/arch/riscv/reg/riscv.rs
Hey,
This PR contains two commits:
- A first that implements the `Arch` trait for RISC-V 32/64 bit
- A second one that add support for the "Read register command" of the RSP protocol ('p' command), this is actually needed for debuging RISC-V programs. GDB is querying some specific CSR registers through this command (mstatus, mpriv, ...).
Currently I have a RISC-V softfp toolchain for testing. I will try to add support for floating-point RISC-V 32 and 64 as well soon.
Let me know if the commits need some rework.
Thanks for your awesome `gdbstub` crate, it works like a charm on my emulator !
Thomas.
> Add (partial) support for RISC-V

- Cargo.toml
`cargo build` fails if cfg-if is 0.1.9 or older.
It seems that [this change](https://github.com/alexcrichton/cfg-if/pull/28) is needed to compile [this part](https://github.com/daniel5151/gdbstub/blob/da716bdd7b/src/protocol/console_output.rs#L43-L48).
> specify cfg-if 0.1.10 or later

- src/arch/x86/mod.rs
- src/arch/x86/reg/id.rs
This is one of action items in issue #29.
> implement `RegId` for x86/x86_64

- src/target/ext/mod.rs
OptExt is a subtrait of Target, not the opposite. See https://doc.rust-lang.org/reference/items/traits.html#supertraits
Also thanks for the read 😄
> Fix trait terminology

- examples/armv4t/gdb/mod.rs
- examples/armv4t/gdb/target_description_xml_override.rs
- src/arch/traits.rs
- src/gdbstub_impl/mod.rs
- src/target/ext/mod.rs
- src/target/ext/target_description_xml_override.rs
- src/target/mod.rs
Building off of @DrChat's work in #42 (closes #42)
Remember how [I said](https://github.com/daniel5151/gdbstub/pull/42#issuecomment-802329081) I'd try and tackle #12 as part of this PR as well? Well... after refreshing myself on the details of the underlying `qXfer:features:read` API, I realized that my idea wouldn't actually work. The changes will require a bit more thought and effort, and aren't something I'd be able to hack out in an afternoon. 
As such, I've kept this PR's scope limited to just allowing target-dependent target description XML files.
> Add `TargetDescriptionXmlOverride` extension

- src/arch/riscv/mod.rs
- src/arch/riscv/reg/id.rs
Hello. For RISC-V 64, the size of Csr and Gpr is 64bit. However, the RiscvRegId's `from_raw_id` returns 4 bytes for both RV32 and RV64. Thus I create a new type for RV64 and re-implement `from_raw_id`. Now, the `RegId::from_raw_id()` works correctly on RV64 architecture.
I am new Rust. I think my implementation is a little ugly but I have no idea how to implement this elegantly. The `RiscvRegId64` and `RiscvRegId` have same definition. I define this new type only for override `from_raw_id`. I have tried to define something like `RiscvRegId<U>`. But the compiler complains that `U` is an unused parameter.
> fix RiscvRegId's from_raw_id for RISCV64

- examples/armv4t/gdb/mod.rs
- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/mod.rs
- src/gdbstub_impl/ext/reverse_exec.rs
- src/gdbstub_impl/mod.rs
- src/protocol/commands.rs
- src/protocol/commands/_bc.rs
- src/protocol/commands/_bs.rs
- src/target/ext/base/mod.rs
- src/target/ext/base/multithread.rs
- src/target/ext/base/singlethread.rs
This is a pull request for reverse continue/step support for gdbstub.
This corresponds to the `bc` / `bs` packets, or the `rs` / `rc` commands in GDB.
> Reverse execution

- examples/armv4t/gdb/memory_map.rs
- examples/armv4t/gdb/mod.rs
- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/memory_map.rs
- src/gdbstub_impl/ext/mod.rs
- src/gdbstub_impl/mod.rs
- src/protocol/commands.rs
- src/protocol/commands/_qXfer_memory_map.rs
- src/target/ext/memory_map.rs
- src/target/ext/mod.rs
- src/target/mod.rs
For embedded targets, we need to be able to configure the memory map, as described in the [GDB Docs].
Otherwise, GDB will try to use software breakpoints for code running from flash, which doesn't work.
This PR adds an extension trait based on the `target_description_xml_override` extension to support memory maps.
[GDB Docs]: https://sourceware.org/gdb/onlinedocs/gdb/Memory-Map-Format.html#Memory-Map-Format
> Add support for memory maps

- gdbstub_arch/src/msp430/mod.rs
- gdbstub_arch/src/msp430/reg/id.rs
- gdbstub_arch/src/msp430/reg/msp430.rs
The previous MSP430 register definition in `gdbstub_arch` was missing a GPR.
This PR adds the missing register as well as adding support for 20-bit MSP430 variant (CPUX) using the paramaterization strategy from the MIPS implementation, note that gdb treats the 20-bit registers as 32-bit registers internally.
I tested both the 16-bit variant and the 20-bit variant with my emulator, and things seemed to work. Backtraces seem to be broken but I don't think that is related gdbstub (The TI compiler was used to compile the binary I was testing, I think it could be an upstream GDB issue with the TI calling convention).
Technically this is breaking API change, however, since the previous implementation would have resulted in R15 being dropped, it seems unlikely it is being used. …
> Msp430 fixes

- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/memory_map.rs
- src/protocol/response_writer.rs
Unify the way of writing a range of data
> Unify the way of writing a range of data

- Cargo.toml
- README.md
- examples/armv4t/emu.rs
- examples/armv4t/gdb/host_io.rs
- examples/armv4t/gdb/mod.rs
- src/common.rs
- src/gdbstub_impl/ext/host_io.rs
- src/gdbstub_impl/ext/mod.rs
- src/gdbstub_impl/mod.rs
- src/protocol/commands.rs
- src/protocol/commands/_vFile_close.rs
- src/protocol/commands/_vFile_fstat.rs
- src/protocol/commands/_vFile_open.rs
- src/protocol/commands/_vFile_pread.rs
- src/protocol/commands/_vFile_pwrite.rs
- src/protocol/commands/_vFile_readlink.rs
- src/protocol/commands/_vFile_setfs.rs
- src/protocol/commands/_vFile_unlink.rs
- src/protocol/common/hex.rs
- src/protocol/console_output.rs
- src/protocol/packet.rs
- src/protocol/response_writer.rs
- src/target/ext/host_io.rs
- src/target/ext/mod.rs
- src/target/mod.rs
Support Host I/O operations 
Refer: #32 
<details>
```
(gdb) remote get /tmp/remote.txt /tmp/local.txt
Successfully fetched file "/tmp/remote.txt".
(gdb) remote put /tmp/local.txt /tmp/remote.txt
Successfully sent file "/tmp/local.txt".
(gdb) remote delete /tmp/remote.txt
Successfully deleted file "/tmp/remote.txt"
```
</details>
<details>
<summary>armv4t output</summary>
```
Finished dev [unoptimized + debuginfo] target(s) in 0.02s
Running `target/debug/examples/armv4t`
loading section ".text" into memory from [0x55550000..0x55550078]
Setting PC to 0x55550000
Waiting for a GDB connection on "127.0.0.1:9001"...
Debugger connected from …
```
> Support Host I/O operations

- README.md
- examples/armv4t/gdb/exec_file.rs
- examples/armv4t/gdb/host_io.rs
- examples/armv4t/gdb/mod.rs
- examples/armv4t/main.rs
- examples/armv4t/test_bin/.gdbinit
- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/exec_file.rs
- src/gdbstub_impl/ext/mod.rs
- src/gdbstub_impl/mod.rs
- src/protocol/commands.rs
- src/protocol/commands/_qXfer_exec_file.rs
- src/protocol/commands/_vFile_setfs.rs
- src/target/ext/exec_file.rs
- src/target/ext/mod.rs
- src/target/mod.rs
> Support read exec-file

- README.md
We have just merged preliminary single core gdb support using gdbstub to uhyve. :tada: 
This PR adds uhyve to the real-world examples in `README.md`.
> README.md: Add uhyve to real-world examples

- examples/armv4t/gdb/exec_file.rs
- examples/armv4t/gdb/host_io.rs
- examples/armv4t/gdb/memory_map.rs
- examples/armv4t/gdb/mod.rs
- examples/armv4t/gdb/target_description_xml_override.rs
- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/host_io.rs
- src/gdbstub_impl/ext/memory_map.rs
- src/protocol/commands.rs
- src/protocol/commands/_qXfer_features_read.rs
- src/protocol/commands/_qXfer_memory_map.rs
- src/protocol/commands/_vFile_pread.rs
- src/protocol/commands/_vFile_readlink.rs
- src/protocol/response_writer.rs
- src/target/ext/host_io.rs
- src/target/ext/memory_map.rs
- src/target/ext/target_description_xml_override.rs
- Update the other qXfer-backed protocol extensions to use the `(length: usize, offset: u64, buf: &mut [u8])` API
- At the moment, I think this is just `MemoryMap` and `TargetXmlOverride`
- Update the vFile API to use the `&mut [u8]` PacketBuf instead of the current callback-based approach.
- Update the vFile API to use plain 'ol `usize` for `length` and `offset` parameters, instead of `Target::Arch::Usize`
- Context: https://github.com/daniel5151/gdbstub/pull/69#discussion_r707477573
_Originally posted by @daniel5151 in https://github.com/daniel5151/gdbstub/issues/69#issuecomment-920159984_
> Pass PacketBuf as an argument of API

- Cargo.toml
- src/protocol/recv_packet.rs
- src/protocol/response_writer.rs
Enable logging for responses (as discussed here https://github.com/daniel5151/gdbstub/discussions/77)
> Enable logging for responses with only alloc.

- example_no_std/src/gdb.rs
- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/mod.rs
- src/gdbstub_impl/ext/x_upcase_packet.rs
- src/gdbstub_impl/mod.rs
- src/protocol/commands.rs
- src/protocol/commands/_x_upcase.rs
- src/target/mod.rs
> Implement X packet for gdbstub.

- README.md
- examples/armv4t/gdb/auxv.rs
- examples/armv4t/gdb/mod.rs
- src/gdbstub_impl/ext/auxv.rs
- src/gdbstub_impl/ext/base.rs
- src/gdbstub_impl/ext/mod.rs
- src/gdbstub_impl/mod.rs
- src/protocol/commands.rs
- src/protocol/commands/_qXfer_auxv_read.rs
- src/protocol/commands/_qXfer_exec_file.rs
- src/protocol/commands/_vFile_close.rs
- src/protocol/commands/_vFile_fstat.rs
- src/protocol/commands/_vFile_open.rs
- src/protocol/commands/_vFile_pread.rs
- src/protocol/commands/_vFile_pwrite.rs
- src/protocol/commands/_vFile_readlink.rs
- src/protocol/commands/_vFile_setfs.rs
- src/protocol/commands/_vFile_unlink.rs
- src/target/ext/auxv.rs
- src/target/ext/memory_map.rs
- src/target/ext/mod.rs
- src/target/ext/target_description_xml_override.rs
- src/target/mod.rs
> Support read auxv

- gdbstub_arch/src/x86/reg/id.rs
Fixes #80.
I ran this in the past but this change was with the github editor :)
> Change rip size to 8 in `X86_64CoreRegId`.

- examples/armv4t/gdb/host_io.rs
- examples/armv4t/gdb/mod.rs
- gdbstub_arch/src/arm/reg/id.rs
- gdbstub_arch/src/mips/reg/id.rs
- gdbstub_arch/src/msp430/reg/id.rs
- gdbstub_arch/src/riscv/reg/id.rs
- gdbstub_arch/src/x86/reg/id.rs
- src/arch.rs
- src/gdbstub_impl/ext/single_register_access.rs
- src/protocol/commands.rs
- src/protocol/commands/_p.rs
- src/target/ext/base/single_register_access.rs
New approach to #58.
Part of #70.
Closes #58. Closes #80.
> Dynamic `read_register` + `RegId` support

- CHANGELOG.md
- src/target/ext/host_io.rs
This PR adds lldb-specific HostIoOpenFlags, as proposed in #99
> add lldb-specific HostIoOpenFlags

- src/stub/core_impl/base.rs
When more than one thread is active the following warning is visible upon connecting:
```
warning: multi-threaded target stopped without sending a thread-id, using first non-exited thread
```
This is because gdbstub sends a stop packet of `S05`, which conveys no thread-id.  This fix changes the response to `T05thread:<tid>;`, which eliminates the warning.
Validated on armv4t and armv4t_multicore
<details>
```
(gdb) target remote localhost:9001
Remote debugging using localhost:9001
0x55550000 in ?? ()
(gdb) 
```
</details>
<details>
<summary>armv4t output</summary>
```
!!!!! EXAMPLE OUTPUT !!!!!
TRACE gdbstub::protocol::recv_packet     > <-- $?#3f
TRACE gdbstub::protocol::response_writer > --> $T05thread:p01.01;#06
``` …
> Report thread-id in response to `?` packet

- README.md
- examples/armv4t_multicore/gdb.rs
- src/protocol/commands.rs
- src/protocol/commands/_qThreadExtraInfo.rs
- src/protocol/common/thread_id.rs
- src/protocol/mod.rs
- src/stub/core_impl.rs
- src/stub/core_impl/thread_extra_info.rs
- src/target/ext/base/multithread.rs
- src/target/ext/mod.rs
- src/target/ext/thread_extra_info.rs
Add a new sub-IDET for `MultiThreadBase` to respond with extra information about a thread.
Closes #104 
<details>
```
(gdb) info thread
Id   Target Id            Frame 
* 1    Thread 1.1 (CPU Cpu) 0x55550000 in ?? ()
2    Thread 1.2 (CPU Cop) 0x55550000 in ?? ()
(gdb) 
```
</details>
<details>
<summary>armv4t output</summary>
```
TRACE gdbstub::protocol::recv_packet     > <-- $qThreadExtraInfo,p1.1#85
TRACE gdbstub::protocol::response_writer > --> $43505520437075#d2
TRACE gdbstub::protocol::recv_packet     > <-- $qThreadExtraInfo,p1.2#86
TRACE gdbstub::protocol::response_writer > --> $43505520436f70#02
```
</details>
> Add support for qThreadExtraInfo

- examples/armv4t/gdb/mod.rs
- examples/armv4t/gdb/register_info_override.rs
- src/arch.rs
- src/protocol/commands.rs
- src/protocol/commands/_qRegisterInfo.rs
- src/protocol/response_writer.rs
- src/stub/core_impl.rs
- src/stub/core_impl/register_info.rs
- src/target/ext/mod.rs
- src/target/ext/register_info_override.rs
- src/target/mod.rs
This implements the LLDB specifc `qRegisterInfo` packet (documentation [here](https://github.com/llvm/llvm-project/blob/50f2e49924566330ea9aa731908f2864603bf4fb/lldb/docs/lldb-gdb-remote.txt#L583)).
Relates to #99 
I was working on a target where I had some trouble getting the .xml target description formatting right so I opted to use the `qRegisterInfo` packet instead which pretty much worked right away. I haven't looked into unifying them as mentioned in the compatibility issue as of now though.
One caveat is that some values in the reply need to be in decimal representation. Due to this I added a `write_dec()` method in the `ResponseWriter` (I'm not sure this was actually necessary). Since this packet is only used by `LLDB` it might be reasonable to just hide it behind a feature flag. …
> add qRegisterInfo packet support

- example_no_std/check_size.sh
As shown in https://github.com/daniel5151/gdbstub/pull/107#issuecomment-1191802780, it was easy to misinterpret the instructions as running the script from the root of the directory (which would break). Make it possible to do so.
> check_size.sh: Allow running script from other dirs

- examples/armv4t/gdb/mod.rs
- examples/armv4t/gdb/target_description_xml_override.rs
- src/stub/core_impl/single_register_access.rs
- src/target/ext/base/single_register_access.rs
Make gdbstub report to the GDB client the state of an unavailable (but valid) register by following the [registers packet protocol](https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#read-registers-packet):
> [...] the stub may also return a string of literal `x`s in place of
> the register data digits, to indicate that the corresponding register
> has not been collected, thus its value is unavailable.
- Validation
<details>
```
(gdb) info registers SPSR_EL3
SPSR_EL3       <unavailable>
```
</details>
<details>
<summary>examples/armv4t</summary>
```
$ RUST_LOG=trace cargo run --example armv4t
Compiling gdbstub v0.6.2 (/usr/local/google/home/ptosi/src/gdbstub)
Finished dev [unoptimized + debuginfo] target(s) in 1.76s
Running …
```
> SingleRegisterAccess: Support unavailable regs

- example_no_std/src/gdb.rs
- examples/armv4t/gdb/mod.rs
- examples/armv4t_multicore/gdb.rs
- src/stub/core_impl/base.rs
- src/target/ext/base/multithread.rs
- src/target/ext/base/singlethread.rs
- src/target/mod.rs
The `read_addrs()` method for targets now returns a number of bytes that were read. This allows a target to gracefully signal the client that memory at an address range is not accessible.
I’ve implemented this functionality for the armv4t example to be able to test it.
Closes #111.
This PR requires a breaking API change.
- ~~(if appropriate) Added feature to "Debugging Features" in README.md~~
- ~~_If implementing a new protocol extension IDET_~~
- ~~_If upstreaming an `Arch` implementation_~~
I’m not sure how to update the changelog.
```
(gdb) x 0x00
0x0:    Cannot access memory at address 0x0
```
```
TRACE gdbstub::protocol::recv_packet     > <-- $m0,4#fd
TRACE gdbstub::protocol::response_writer > --> $#00
```
```
(gdb) x/4xb 0x6554fffe
0x6554fffe: …
```
> `read_addrs()` can return fewer bytes than requested

- src/protocol/commands/_x_upcase.rs
> X packets contains `, || :` in the payload

- gdbstub_arch/src/riscv/mod.rs
GDB on Risc-V seems to unconditionally ask for single-stepping even if we advertise that we don't support it.
> riscv: mark arch as SingleStepGdbBehavior::Required

- src/protocol/commands.rs
- src/protocol/commands/_qC.rs
- src/stub/core_impl/base.rs
- src/stub/core_impl/extended_mode.rs
- src/stub/core_impl/resume.rs
- src/target/ext/base/multithread.rs
- src/target/ext/extended_mode.rs
This PR implements one possible approach to getting `vAttach` working with multiple processes. With this, it is now possible to attach to a given process, for example by issuing `attach 7` to attach to PID 7.
- Validation
<details>
```
(gdb) tar ext :3456
Remote debugging using :3456
[remote] start_remote_1: enter
[remote] Sending packet: $qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+;memory-tagging+#ec
[remote] Received Ack
[remote] Packet received: PacketSize=1000;vContSupported+;multiprocess+;QStartNoAckMode+;qXfer:features:read+
[remote] packet_ok: Packet qSupported (supported-packets) is supported
[remote] Sending packet: $vMustReplyEmpty#3a …
```
> vAttach: get vAttach working with multi-process

- examples/armv4t/emu.rs
- examples/armv4t/gdb/extended_mode.rs
- src/lib.rs
- src/protocol/commands.rs
- src/stub/core_impl/base.rs
- src/stub/core_impl/extended_mode.rs
- src/stub/core_impl/resume.rs
- src/stub/error.rs
- src/target/ext/base/multithread.rs
- src/target/ext/extended_mode.rs
Follow up to #129 
Spent some time reworking the implementation in order to:
1. crunch down the binary size of targets uninterested in this functionality.
2. allow using vAttach on single-threaded targets
There are some "warts" in this implementation, owing to the fact that I'd like to land this as part of a non-breaking `0.6.x` release. Namely: the runtime bound that only allows using `attach` if `CurrentActivePid` is implemented.
Assuming we're happy with this PR, I'll open a follow-up tracking issue to resolve these API warts in 0.7.x.
- Validation
<details>
```
(gdb) target extended-remote :9001
Remote debugging using :9001
Reading /test.elf from remote target...
warning: File transfers …
```
> Rework vAttach + custom pid reporting

- example_no_std/src/gdb.rs
- src/protocol/commands.rs
- src/stub/core_impl.rs
- src/stub/core_impl/base.rs
- src/stub/core_impl/no_ack_mode.rs
- src/target/mod.rs
This PR makes the feature `QStartNoAckMode` toggleable.
Closes #134
- Validation
<details>
<summary>Before/After `./example_no_std/check_size.sh` output</summary>
```
target/release/gdbstub-nostd  :
section               size    addr
.interp                 28     792
.note.gnu.property      32     824
.note.gnu.build-id      36     856
.note.ABI-tag           32     892
.gnu.hash               28     928
.dynsym                360     960
.dynstr                204    1320
.gnu.version            30    1524
.gnu.version_r          64    1560
.rela.dyn              408    1624
.init                   27    4096
.text                15158    4128
.fini                   13   19288 …
```
> Toggle support for `QStartNoAckMode`

- Cargo.toml
- src/stub/core_impl.rs
- src/target/ext/host_io.rs
> Updated to bitflags 2.2.1.

- gdbstub_arch/src/riscv/mod.rs
- gdbstub_arch/src/riscv/rv32i.xml
- gdbstub_arch/src/riscv/rv64i.xml
lldb requires a full list of registers in the target_description_xml (gdb on the other hand seems to ignore the list completely).
The gdb manual sounds like these registers should exist anyway:
> The ‘org.gnu.gdb.riscv.cpu’ feature is required for RISC-V targets. It should contain the registers ‘x0’ through ‘x31’, and ‘pc’.
Therefore it seems reasonable that the RISC-V arch returns the full list.
<details>
<summary>LLDB output (before this change)</summary>
```
~/source/my_emulator % lldb target/last-image
(lldb) target create "target/last-image"
Current executable set to '/Users/daniel/source/my_emulator/target/last-image' (riscv32).
(lldb) gdb-remote localhost:9002
Process 1 stopped
* thread #1, stop reason = signal SIGTRAP
frame #0: …
```
> RISC-V: List all integer registers for lldb compatibility

- Cargo.toml
- README.md
- src/lib.rs
- src/stub/error.rs
- src/target/mod.rs
Not sure if the validation outputs are required because it is a small change.
Closes #153.
> feature to use core::error::Error instead of std::error::Error

- README.md
- examples/armv4t/emu.rs
- examples/armv4t/gdb/mod.rs
- examples/armv4t/gdb/tracepoints.rs
- examples/armv4t/main.rs
- src/protocol/commands.rs
- src/protocol/commands/_QTBuffer.rs
- src/protocol/commands/_QTDP.rs
- src/protocol/commands/_QTDPsrc.rs
- src/protocol/commands/_QTFrame.rs
- src/protocol/commands/_QTStart.rs
- src/protocol/commands/_QTStop.rs
- src/protocol/commands/_QTinit.rs
- src/protocol/commands/_qTBuffer.rs
- src/protocol/commands/_qTP.rs
- src/protocol/commands/_qTStatus.rs
- src/protocol/commands/_qTfP.rs
- src/protocol/commands/_qTfV.rs
- src/protocol/commands/_qTsP.rs
- src/protocol/commands/_qTsV.rs
- src/stub/core_impl.rs
- src/stub/core_impl/base.rs
- src/stub/core_impl/tracepoints.rs
- src/stub/error.rs
- src/target/ext/mod.rs
- src/target/ext/tracepoints.rs
- src/target/mod.rs
This PR adds basic [tracepoint extension](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Tracepoints.html) support to GDB stub. Closes #157. 
- Validation
<details>
```
(gdb) trace test.c:10
Tracepoint 1 at 0x55550040: file test.c, line 10.
(gdb) break *0x55550044
Breakpoint 2 at 0x55550044: file test.c, line 10.
(gdb) break main
Breakpoint 3 at 0x5555000c: file test.c, line 2.
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: target:/test.elf 
Reading /test.elf from remote target...
Breakpoint 3, main () at test.c:2
2	in test.c
(gdb) tstart
warning: Target does not support …
```
> Tracepoint extension support

- gdbstub_arch/src/x86/reg/core32.rs
- gdbstub_arch/src/x86/reg/core64.rs
Turns out these were actually Linux-specific registers, namely `orig_eax` for 32-bit and `orig_eax`/`fs_base`/`gs_base` for 64-bit. GDB will gracefully handle a too-short packet but not a too-long one, so removing this padding should make this work for all x86 targets and not just Linux.
Fixes #165
- Validation
Sorry, I've lost my terminal output from when I tested this, but I observed the following with the GDB server implementation at https://github.com/encounter/retrowin32/tree/gdb-stub (32-bit Windows x86)
* no change + `set osabi GNU/Linux`: everything fine
* no change + `set osabi none`: GDB crashes with `Remote 'g' packet reply is too long`
* this change + `set osabi …
> Remove "padding" bytes from x86 register packet

- src/target/ext/tracepoints.rs
Adds a gated import of toOwned which allows tracepoints to compile properly in a no_std environment. 
Closes #173  
- Validation
Changes are super minimal and definitely allows it to build in a no_std env. I will try and actually test changes and add comments with validation output soon.
> Fix to tracepoints no_std per daniel5151's rec in issue 173
